apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chat-app
spec:
  type: NodePort         # ← CHANGE THIS (ClusterIP → NodePort)
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080    # ← OPTIONAL FIXED PORT (you can change)
