apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-backend
  namespace: argocd
spec:
  project: chat-project
  source:
    repoURL: https://github.com/smit-darji/Chat-application.git
    targetRevision: Master
    path: .
    directory:
      recurse: true
      include: backend-*.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
